// Pure learnset helpers, safe to import from client components (unlike
// data.ts, which reads from the filesystem). The data is loaded server-side
// via getLearnset()/getMoveset()/getMoves() in data.ts and passed as props.
import type { Lang } from "@/lib/i18n/dictionary";

// pokemonId (as string key) -> { attackType: minLevel } for DAMAGING level-up
// moves only. Generated by scripts/generate-learnsets.mjs.
export type Learnset = Record<string, Record<string, number>>;

// pokemonId -> [[level, moveSlug], ...] for ALL level-up moves (status too).
export type Moveset = Record<string, [number, string][]>;

// moveSlug -> localized names + type + damage class.
export type MoveInfo = { type: string; damaging: boolean; names: Record<string, string> };
export type MovesTable = Record<string, MoveInfo>;

export type MoveEntry = { level: number; name: string; type: string; damaging: boolean };

// PokeAPI's `moves.json` type is always the move's CURRENT (latest-generation)
// type; a handful of moves were retyped at some point in the games' history
// (data/move-type-history.json, hand-curated from PokeAPI's move `past_values`
// - see scripts/generate-learnsets.mjs). `maxGeneration` = the type applied
// through that generation (inclusive).
export type MoveTypeHistoryEntry = { slug: string; type: string; maxGeneration: number };

// The type a move actually had in the given generation, correcting for
// historical retypes (e.g. Bite was Normal before Gen 3, Charm was Normal
// before Fairy existed in Gen 6). Falls back to `currentType` when no
// override applies.
export function historicalMoveType(
  history: MoveTypeHistoryEntry[],
  slug: string,
  generation: number,
  currentType: string,
): string {
  const entry = history.find((h) => h.slug === slug && generation <= h.maxGeneration);
  return entry?.type ?? currentType;
}

// moveSlug -> which Pokémon can OFFICIALLY learn it via machine (TM/HM) or a
// move tutor, per version group. Generated by scripts/generate-learnsets.mjs
// (data/tm-compat/<vg>.json) - drives the TM-compatibility tab.
export type TmLearnMethod = "tm" | "hm" | "tutor";
export type TmCompatEntry = {
  machine?: { kind: "tm" | "hm"; ids: number[] };
  tutor?: number[];
};
export type TmCompatTable = Record<string, TmCompatEntry>;

// How a given Pokémon can officially learn a move (TM, HM, and/or tutor).
// Empty = not learnable by machine/tutor in this game.
export function tmLearnMethods(
  entry: TmCompatEntry | undefined,
  pokemonId: number,
): TmLearnMethod[] {
  if (!entry) return [];
  const methods: TmLearnMethod[] = [];
  if (entry.machine?.ids.includes(pokemonId)) methods.push(entry.machine.kind);
  if (entry.tutor?.includes(pokemonId)) methods.push("tutor");
  return methods;
}

// A Pokémon's level-up moves up to the given level, localized, sorted by level.
export function moveListAtLevel(
  moveset: Moveset,
  moves: MovesTable,
  pokemonId: number,
  level: number,
  lang: Lang,
  generation: number,
  moveTypeHistory: MoveTypeHistoryEntry[],
): MoveEntry[] {
  const list = moveset[String(pokemonId)];
  if (!list) return [];
  return list
    .filter(([lvl]) => lvl <= level)
    .map(([lvl, slug]) => {
      const info = moves[slug];
      return {
        level: lvl,
        name: info?.names[lang] ?? info?.names.en ?? slug,
        type: historicalMoveType(moveTypeHistory, slug, generation, info?.type ?? "normal"),
        damaging: info?.damaging ?? true,
      };
    });
}

// The self-destruct / explosion move a Pokémon can learn (lowest level), or
// null. Powers the Battle tab's "can go boom" warning.
export function explosiveMove(
  moveset: Moveset,
  moves: MovesTable,
  pokemonId: number,
  lang: Lang,
): { slug: string; level: number; name: string } | null {
  const list = moveset[String(pokemonId)];
  if (!list) return null;
  let best: { slug: string; level: number; name: string } | null = null;
  for (const [lvl, slug] of list) {
    if (slug !== "self-destruct" && slug !== "explosion") continue;
    if (!best || lvl < best.level) {
      best = { slug, level: lvl, name: moves[slug]?.names[lang] ?? moves[slug]?.names.en ?? slug };
    }
  }
  return best;
}

// A Pokémon's damaging attack types reachable by the given level, each with
// the lowest level it's first learned, sorted by that level then name.
export function attackTypesAtLevel(
  learnset: Learnset,
  pokemonId: number,
  level: number,
): { type: string; level: number }[] {
  const entry = learnset[String(pokemonId)];
  if (!entry) return [];
  return Object.entries(entry)
    .filter(([, lvl]) => lvl <= level)
    .map(([type, lvl]) => ({ type, level: lvl }))
    .sort((a, b) => a.level - b.level || a.type.localeCompare(b.type));
}
