import type { Lang } from "@/lib/i18n/dictionary";

export const TYPE_LABELS: Record<Lang, Record<string, string>> = {
  de: {
    normal: "Normal",
    fire: "Feuer",
    water: "Wasser",
    electric: "Elektro",
    grass: "Pflanze",
    ice: "Eis",
    fighting: "Kampf",
    poison: "Gift",
    ground: "Boden",
    flying: "Flug",
    psychic: "Psycho",
    bug: "Käfer",
    rock: "Gestein",
    ghost: "Geist",
    dragon: "Drache",
    dark: "Unlicht",
    steel: "Stahl",
    fairy: "Fee",
    // Curse's pre-Gen-6 type ("???" in-game) - see move-type-history.json.
    unknown: "???",
  },
  en: {
    normal: "Normal",
    fire: "Fire",
    water: "Water",
    electric: "Electric",
    grass: "Grass",
    ice: "Ice",
    fighting: "Fighting",
    poison: "Poison",
    ground: "Ground",
    flying: "Flying",
    psychic: "Psychic",
    bug: "Bug",
    rock: "Rock",
    ghost: "Ghost",
    dragon: "Dragon",
    dark: "Dark",
    steel: "Steel",
    fairy: "Fairy",
    unknown: "???",
  },
  fr: {
    normal: "Normal",
    fire: "Feu",
    water: "Eau",
    electric: "Électrik",
    grass: "Plante",
    ice: "Glace",
    fighting: "Combat",
    poison: "Poison",
    ground: "Sol",
    flying: "Vol",
    psychic: "Psy",
    bug: "Insecte",
    rock: "Roche",
    ghost: "Spectre",
    dragon: "Dragon",
    dark: "Ténèbres",
    steel: "Acier",
    fairy: "Fée",
    unknown: "???",
  },
  es: {
    normal: "Normal",
    fire: "Fuego",
    water: "Agua",
    electric: "Eléctrico",
    grass: "Planta",
    ice: "Hielo",
    fighting: "Lucha",
    poison: "Veneno",
    ground: "Tierra",
    flying: "Volador",
    psychic: "Psíquico",
    bug: "Bicho",
    rock: "Roca",
    ghost: "Fantasma",
    dragon: "Dragón",
    dark: "Siniestro",
    steel: "Acero",
    fairy: "Hada",
    unknown: "???",
  },
  it: {
    normal: "Normale",
    fire: "Fuoco",
    water: "Acqua",
    electric: "Elettro",
    grass: "Erba",
    ice: "Ghiaccio",
    fighting: "Lotta",
    poison: "Veleno",
    ground: "Terra",
    flying: "Volante",
    psychic: "Psico",
    bug: "Coleottero",
    rock: "Roccia",
    ghost: "Spettro",
    dragon: "Drago",
    dark: "Buio",
    steel: "Acciaio",
    fairy: "Folletto",
    unknown: "???",
  },
};

// Gen 1 predates the Steel type: the Magnemite line was pure Electric.
// (No Gen-1 Pokémon carries Dark; Fairy/Gen 6+ is out of scope.) pokemon.json
// stores the Gen-3 typing, so Gen-1 runs correct it at display/calc time.
const GEN1_TYPE_OVERRIDES: Record<number, string[]> = {
  81: ["electric"],
  82: ["electric"],
};

export function typesForGeneration(
  pokemonId: number,
  types: string[],
  generation: number,
): string[] {
  if (generation === 1) return GEN1_TYPE_OVERRIDES[pokemonId] ?? types;
  return types;
}

export const TYPE_COLORS: Record<string, string> = {
  normal: "#A8A878",
  fire: "#F08030",
  water: "#6890F0",
  electric: "#F8D030",
  grass: "#78C850",
  ice: "#98D8D8",
  fighting: "#C03028",
  poison: "#A040A0",
  ground: "#E0C068",
  flying: "#A890F0",
  psychic: "#F85888",
  bug: "#A8B820",
  rock: "#B8A038",
  ghost: "#705898",
  dragon: "#7038F8",
  dark: "#705848",
  steel: "#B8B8D0",
  fairy: "#EE99AC",
  // Curse's pre-Gen-6 "???" type - a defunct oddity, not a real battling type.
  unknown: "#68A090",
};
