import type { Pokemon, PokemonStats } from "@/lib/data";

// PokeAPI serves each Pokémon's CURRENT types and base stats, and a lot of
// both changed after Gen 5 - the era this app stops at. Three distinct things
// leak through if nothing corrects them:
//
//   * Fairy. It did not exist before Gen 6, yet Togekiss, Marill, Gardevoir,
//     Whimsicott and 20 others carry it today. A Gen 1-5 run must never show
//     the type at all.
//   * The Rotom formes. Gen 5 gave them their appliance types; in Gen 4
//     (Platinum, HeartGold/SoulSilver) all five were plain Electric/Ghost.
//   * Base stats. Gen 6 handed ~30 Pokémon a flat +10 buff, which silently
//     shifts BST, the Pokédex ranking, `maxEvolvedSumme` and every team
//     strength comparison in the app.
//
// data/pokemon-history.json is generated by scripts/generate-pokemon-history.mjs
// from PokeAPI's own `past_types`/`past_stats`, using the same maxGeneration
// convention as the move and catch-rate tables: "this value applied through
// that generation, inclusive".
export type PokemonHistoryEntry = {
  id: number;
  maxGeneration: number;
  types?: string[];
  // PokeAPI's stat vocabulary, mapped to pokemon.json's German keys below so
  // the data file carries no display concerns.
  stats?: Partial<Record<string, number>>;
};

const STAT_KEYS: Record<string, keyof PokemonStats> = {
  hp: "KP",
  attack: "Ang.",
  defense: "Vert.",
  "special-attack": "Sp.-A.",
  "special-defense": "Sp.-V.",
  speed: "Init.",
  // Deliberately absent: "special". Gen 1 had a single Special stat governing
  // both attack and defence, which this app's six-stat model cannot express -
  // mapping it onto Sp.-A. AND Sp.-V. would double-count it in `Summe` and put
  // every Gen-1 BST well above the real one. The generated file keeps those
  // entries so the decision stays reversible; see the note in CLAUDE.md.
};

// The types and base stats a Pokémon actually had in the given generation.
// Returns the input object unchanged when nothing applies, so callers can rely
// on referential equality to skip work.
export function pokemonForGeneration(
  history: PokemonHistoryEntry[],
  pokemon: Pokemon,
  generation: number,
): Pokemon {
  let types: string[] | undefined;
  let stats: PokemonStats | undefined;

  for (const entry of history) {
    if (entry.id !== pokemon.id || generation > entry.maxGeneration) continue;

    if (entry.types) types = entry.types;

    if (entry.stats) {
      const next: PokemonStats = { ...(stats ?? pokemon.stats) };
      for (const [apiKey, value] of Object.entries(entry.stats)) {
        const key = STAT_KEYS[apiKey];
        if (key && value !== undefined) next[key] = value;
      }
      // Summe is stored rather than derived, so it has to be recomputed or the
      // card would show six stats that do not add up to their own total.
      next.Summe = next.KP + next["Ang."] + next["Vert."] + next["Sp.-A."] + next["Sp.-V."] + next["Init."];
      stats = next;
    }
  }

  if (!types && !stats) return pokemon;
  return { ...pokemon, ...(types ? { types } : {}), ...(stats ? { stats } : {}) };
}

// Convenience for a whole list; keeps the untouched entries by reference.
export function pokemonListForGeneration(
  history: PokemonHistoryEntry[],
  list: Pokemon[],
  generation: number,
): Pokemon[] {
  if (history.length === 0) return list;
  return list.map((pokemon) => pokemonForGeneration(history, pokemon, generation));
}
