import type { Pokemon, PokemonStats } from "@/lib/data";

// PokeAPI serves each Pokémon's CURRENT types and base stats, and a lot of
// both changed after Gen 5 - the era this app stops at. Three distinct things
// leak through if nothing corrects them:
//
//   * Fairy. It did not exist before Gen 6, yet Togekiss, Marill, Gardevoir,
//     Whimsicott and 20 others carry it today. A Gen 1-5 run must never show
//     the type at all.
//   * The Rotom formes. Gen 5 gave them their appliance types; in Gen 4
//     (Platinum, HeartGold/SoulSilver) all five were plain Electric/Ghost.
//   * Base stats. Gen 6 handed ~30 Pokémon a flat +10 buff, which silently
//     shifts BST, the Pokédex ranking, `maxEvolvedSumme` and every team
//     strength comparison in the app.
//
// data/pokemon-history.json is generated by scripts/generate-pokemon-history.mjs
// from PokeAPI's own `past_types`/`past_stats`, using the same maxGeneration
// convention as the move and catch-rate tables: "this value applied through
// that generation, inclusive".
export type PokemonHistoryEntry = {
  id: number;
  maxGeneration: number;
  types?: string[];
  // PokeAPI's stat vocabulary, mapped to pokemon.json's German keys below so
  // the data file carries no display concerns.
  stats?: Partial<Record<string, number>>;
};

const STAT_KEYS: Record<string, keyof PokemonStats> = {
  hp: "KP",
  attack: "Ang.",
  defense: "Vert.",
  "special-attack": "Sp.-A.",
  "special-defense": "Sp.-V.",
  speed: "Init.",
};

// Gen 1 handled separately: it had ONE Special stat driving both special
// attack and special defence, and its base stat total counts that value once
// (Mewtwo is 106/110/90/154/130 = 590, not the 680 the split-era numbers give).
// So a Gen-1 game gets `Spezial` set - which is what makes the UI collapse the
// two special rows into one - plus Sp.-A./Sp.-V. mirrored to the same number so
// any generic consumer still reads a truthful per-stat value.
const GEN1_SPECIAL = "special";

// The types and base stats a Pokémon actually had in the given generation.
// Returns the input object unchanged when nothing applies, so callers can rely
// on referential equality to skip work.
export function pokemonForGeneration(
  history: PokemonHistoryEntry[],
  pokemon: Pokemon,
  generation: number,
): Pokemon {
  let types: string[] | undefined;
  let stats: PokemonStats | undefined;

  // Several entries can cover the same generation - Pikachu has one for its
  // Gen-1 Special AND one for the Gen-6 Defence buff, and both apply when
  // rendering a Gen-1 game. Applying them from the widest window to the
  // narrowest lets the most specific one win: without this the Gen-5 entry
  // would overwrite the Gen-1 Special that was set first.
  const applicable = history
    .filter((entry) => entry.id === pokemon.id && generation <= entry.maxGeneration)
    .sort((a, b) => b.maxGeneration - a.maxGeneration);

  for (const entry of applicable) {
    if (entry.types) types = entry.types;

    if (entry.stats) {
      const next: PokemonStats = { ...(stats ?? pokemon.stats) };
      for (const [apiKey, value] of Object.entries(entry.stats)) {
        if (value === undefined) continue;
        if (apiKey === GEN1_SPECIAL) {
          next.Spezial = value;
          next["Sp.-A."] = value;
          next["Sp.-V."] = value;
          continue;
        }
        const key = STAT_KEYS[apiKey];
        if (key) next[key] = value;
      }
      // Summe is stored rather than derived, so it has to be recomputed - and
      // with the Gen-1 Special counted ONCE, or every Gen-1 total would come
      // out roughly a hundred points too high.
      next.Summe =
        next.KP +
        next["Ang."] +
        next["Vert."] +
        next["Init."] +
        (next.Spezial !== undefined ? next.Spezial : next["Sp.-A."] + next["Sp.-V."]);
      stats = next;
    }
  }

  if (!types && !stats) return pokemon;
  return { ...pokemon, ...(types ? { types } : {}), ...(stats ? { stats } : {}) };
}

// Convenience for a whole list; keeps the untouched entries by reference.
export function pokemonListForGeneration(
  history: PokemonHistoryEntry[],
  list: Pokemon[],
  generation: number,
): Pokemon[] {
  if (history.length === 0) return list;
  return list.map((pokemon) => pokemonForGeneration(history, pokemon, generation));
}
