import type { Lang } from "@/lib/i18n/dictionary";
import type { Pokemon, Route, LevelCap } from "@/lib/data";

// Display names in the data files are objects keyed by language. de/en are
// hand-curated and always present; the other languages are generated by
// scripts/generate-names.mjs and may be missing for edge cases - hence the
// fallback chain lang -> en -> de.
export type LocalizedNames = { de: string; en: string } & Partial<Record<Lang, string>>;

export function localizeName(names: LocalizedNames, lang: Lang): string {
  return names[lang] ?? names.en ?? names.de;
}

export function pokemonName(p: Pokemon, lang: Lang): string {
  return localizeName(p.names, lang);
}

export function routeName(r: Route, lang: Lang): string {
  return localizeName(r.names, lang);
}

export function levelCapName(c: LevelCap, lang: Lang): string {
  return localizeName(c.names, lang);
}

export function levelCapLocation(c: LevelCap, lang: Lang): string {
  return localizeName(c.location, lang);
}

export function levelCapBadge(c: LevelCap, lang: Lang): string | null {
  return c.badge ? localizeName(c.badge, lang) : null;
}
